application:
  name: Tworld Direct Batch Project
  title: Tworld Direct Batch Project (sub-servicename)
  formatted-version: 0.0.1

server:
  port: 10012

spring:
  profiles:
      active: default
  application:
    name: Tworld_Direct_Batch_Project
  main:
    allow-bean-definition-overriding: true

  tomcat:
    accesslog:
      pattern: ACC|%a "%{X-Forwarded-For}i" %l %u %t %s_code %B_bytes %D_usecs "%r" "%{Referer}i" "%{User-Agent}i"
      directory: /proc/self/fd
      prefix: 1
      suffix: ""
      file-date-format: ""
      enabled: true
    basedir: .

batch:
  retry:
    initInterval: 1000 # 최초 1초 대기
    maxInterval: 10000 # 최대 10초 이후는 계속 10초 후에 재시도
    multiplier: 2 # 2배초 만큼 시간이 늘어난다.